project_id = "szjshhhdnriqjedufvsy"

[functions.generate-recurring-tasks]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.check-task-deadlines]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = true

[functions.ai-execute-action]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.check-incomplete-profiles]
verify_jwt = false

[functions.admin-get-user-by-email]
verify_jwt = true

[functions.admin-setup-super-admin]
verify_jwt = true

[functions.check-user-blocked]
verify_jwt = false

[functions.admin-delete-workspace]
verify_jwt = true
